CREATE TABLE IF NOT EXISTS T_PAYS 
(
	CODE VARCHAR(3) PRIMARY KEY,
	NOM_PAYS_COURT VARCHAR(30), 
	CODE_PAYS_2 VARCHAR(2), 
	CODE_PAYS_3 VARCHAR(3), 
	PAYS_NUMERO VARCHAR(3), 
	PAYS_LANGUE VARCHAR(20), 
	LANG VARCHAR(2), 
	PAYS_CONTINENT_ID VARCHAR(2), 
	STATUS VARCHAR(1)
);