version: '3'
services:
  jenkins:
    hostname: jenkins
    image: jenkinsci/blueocean
    ports:
      - 9090:8080
    networks:
      - devops-network

  sonar:
    hostname: sonar
    image: sonarqube
    ports:
      - 9000:9000
    networks:
      - devops-network

networks:
  devops-network:
